all: TAREA_SO mejor

TAREA_SO:
			gcc TAREA_SO.c -o programa -lm
			./programa

mejor:
			gcc mejor.c -o programa2 -lm
			./programa2

clean:
	rm -f programa
	rm -f programa2
	rm -rf horizontal
	rm -rf vertical